export const SKILLS = {
    languages: [
        { name: 'JavaScript', icon: 'javascript' },
        { name: 'TypeScript', icon: 'typescript' },
        { name: 'Python', icon: 'python' },
        { name: 'Java', icon: 'java' },
        { name: 'C', icon: 'c' },
        { name: 'C++', icon: 'cplusplus' },
        { name: 'C#', icon: 'csharp' },
        { name: 'Go', icon: 'go' },
        { name: 'Rust', icon: 'rust' },
        { name: 'Ruby', icon: 'ruby' },
        { name: 'PHP', icon: 'php' },
        { name: 'Swift', icon: 'swift' },
        { name: 'Kotlin', icon: 'kotlin' },
        { name: 'Dart', icon: 'dart' },
        { name: 'Scala', icon: 'scala' },
        { name: 'R', icon: 'r' },
        { name: 'Lua', icon: 'lua' },
        { name: 'Perl', icon: 'perl' },
        { name: 'Haskell', icon: 'haskell' },
        { name: 'Elixir', icon: 'elixir' },
        { name: 'Clojure', icon: 'clojure' },
        { name: 'Julia', icon: 'julia' },
        { name: 'Objective-C', icon: 'objectivec' },
        { name: 'Assembly', icon: 'assembly' },
        { name: 'Solidity', icon: 'solidity' },
        { name: 'MATLAB', icon: 'matlab' },
        { name: 'Bash', icon: 'bash' },
        { name: 'PowerShell', icon: 'powershell' },
    ],
    frameworks: [
        { name: 'React', icon: 'react' },
        { name: 'Next.js', icon: 'nextjs' },
        { name: 'Vue.js', icon: 'vuejs' },
        { name: 'Nuxt.js', icon: 'nuxtjs' },
        { name: 'Angular', icon: 'angular' },
        { name: 'Svelte', icon: 'svelte' },
        { name: 'Node.js', icon: 'nodejs' },
        { name: 'Express', icon: 'express' },
        { name: 'NestJS', icon: 'nestjs' },
        { name: 'Django', icon: 'django' },
        { name: 'Flask', icon: 'flask' },
        { name: 'FastAPI', icon: 'fastapi' },
        { name: 'Spring', icon: 'spring' },
        { name: 'Rails', icon: 'rails' },
        { name: 'Laravel', icon: 'laravel' },
        { name: 'ASP.NET', icon: 'dotnet' },
        { name: 'Flutter', icon: 'flutter' },
        { name: 'React Native', icon: 'react' },
        { name: 'Electron', icon: 'electron' },
        { name: 'Tauri', icon: 'tauri' },
        { name: 'Qt', icon: 'qt' },
        { name: 'Remix', icon: 'remix' },
        { name: 'Astro', icon: 'astro' },
        { name: 'Gatsby', icon: 'gatsby' },
        { name: 'Hugo', icon: 'hugo' },
        { name: 'Tailwind CSS', icon: 'tailwindcss' },
        { name: 'Bootstrap', icon: 'bootstrap' },
        { name: 'Material UI', icon: 'materialui' },
        { name: 'Chakra UI', icon: 'chakraui' },
        { name: 'Styled Components', icon: 'styledcomponents' },
        { name: 'Sass', icon: 'sass' },
        { name: 'Redux', icon: 'redux' },
        { name: 'GraphQL', icon: 'graphql' },
        { name: 'Apollo', icon: 'apollographql' },
        { name: 'tRPC', icon: 'trpc' },
        { name: 'Prisma', icon: 'prisma' },
        { name: 'Drizzle', icon: 'drizzle' },
        { name: 'Socket.io', icon: 'socketio' },
        { name: 'Three.js', icon: 'threejs' },
        { name: 'TensorFlow', icon: 'tensorflow' },
        { name: 'PyTorch', icon: 'pytorch' },
        { name: 'Keras', icon: 'keras' },
        { name: 'OpenCV', icon: 'opencv' },
        { name: 'Pandas', icon: 'pandas' },
        { name: 'NumPy', icon: 'numpy' },
        { name: 'Scikit-learn', icon: 'scikitlearn' },
    ],
    tools: [
        { name: 'Git', icon: 'git' },
        { name: 'GitHub', icon: 'github' },
        { name: 'GitLab', icon: 'gitlab' },
        { name: 'Bitbucket', icon: 'bitbucket' },
        { name: 'Docker', icon: 'docker' },
        { name: 'Kubernetes', icon: 'kubernetes' },
        { name: 'AWS', icon: 'amazonwebservices' },
        { name: 'Azure', icon: 'azure' },
        { name: 'Google Cloud', icon: 'googlecloud' },
        { name: 'Vercel', icon: 'vercel' },
        { name: 'Netlify', icon: 'netlify' },
        { name: 'Heroku', icon: 'heroku' },
        { name: 'DigitalOcean', icon: 'digitalocean' },
        { name: 'Cloudflare', icon: 'cloudflare' },
        { name: 'Firebase', icon: 'firebase' },
        { name: 'Supabase', icon: 'supabase' },
        { name: 'MongoDB', icon: 'mongodb' },
        { name: 'PostgreSQL', icon: 'postgresql' },
        { name: 'MySQL', icon: 'mysql' },
        { name: 'Redis', icon: 'redis' },
        { name: 'SQLite', icon: 'sqlite' },
        { name: 'Elasticsearch', icon: 'elasticsearch' },
        { name: 'Nginx', icon: 'nginx' },
        { name: 'Apache', icon: 'apache' },
        { name: 'Linux', icon: 'linux' },
        { name: 'Ubuntu', icon: 'ubuntu' },
        { name: 'Debian', icon: 'debian' },
        { name: 'macOS', icon: 'apple' },
        { name: 'Windows', icon: 'windows11' },
        { name: 'VS Code', icon: 'vscode' },
        { name: 'IntelliJ', icon: 'intellij' },
        { name: 'Vim', icon: 'vim' },
        { name: 'Neovim', icon: 'neovim' },
        { name: 'Figma', icon: 'figma' },
        { name: 'Adobe XD', icon: 'xd' },
        { name: 'Photoshop', icon: 'photoshop' },
        { name: 'Illustrator', icon: 'illustrator' },
        { name: 'Blender', icon: 'blender' },
        { name: 'Unity', icon: 'unity' },
        { name: 'Unreal Engine', icon: 'unrealengine' },
        { name: 'Postman', icon: 'postman' },
        { name: 'Insomnia', icon: 'insomnia' },
        { name: 'Jest', icon: 'jest' },
        { name: 'Cypress', icon: 'cypress' },
        { name: 'Playwright', icon: 'playwright' },
        { name: 'Selenium', icon: 'selenium' },
        { name: 'Jenkins', icon: 'jenkins' },
        { name: 'CircleCI', icon: 'circleci' },
        { name: 'GitHub Actions', icon: 'githubactions' },
        { name: 'Terraform', icon: 'terraform' },
        { name: 'Ansible', icon: 'ansible' },
        { name: 'Grafana', icon: 'grafana' },
        { name: 'Prometheus', icon: 'prometheus' },
        { name: 'Datadog', icon: 'datadog' },
        { name: 'Sentry', icon: 'sentry' },
        { name: 'Jira', icon: 'jira' },
        { name: 'Notion', icon: 'notion' },
        { name: 'Slack', icon: 'slack' },
        { name: 'Discord', icon: 'discord' },
        { name: 'Webpack', icon: 'webpack' },
        { name: 'Vite', icon: 'vite' },
        { name: 'Babel', icon: 'babel' },
        { name: 'ESLint', icon: 'eslint' },
        { name: 'Prettier', icon: 'prettier' },
        { name: 'npm', icon: 'npm' },
        { name: 'Yarn', icon: 'yarn' },
        { name: 'pnpm', icon: 'pnpm' },
        { name: 'Bun', icon: 'bun' },
    ],
};

export const THEMES = [
    'default',
    'dark',
    'radical',
    'merko',
    'gruvbox',
    'tokyonight',
    'onedark',
    'cobalt',
    'synthwave',
    'highcontrast',
    'dracula',
    'monokai',
    'vue',
    'vue-dark',
    'shades-of-purple',
    'nightowl',
    'buefy',
    'blue-green',
    'algolia',
    'great-gatsby',
    'darcula',
    'bear',
    'solarized-dark',
    'solarized-light',
    'chartreuse-dark',
    'nord',
    'gotham',
    'material-palenight',
    'graywhite',
    'vision-friendly-dark',
    'aura-dark',
    'midnight-purple',
    'calm',
    'flag-india',
    'omni',
    'react',
    'jolly',
    'maroongold',
    'ocean_dark',
    'city_lights',
    'github_dark',
    'github_dark_dimmed',
    'transparent',
];
